-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for Skills/Protocols
create table skills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  short_description text, -- Brief description for card display
  price numeric default 0,
  file_url text, -- Path to the .md file in Storage
  author_id uuid references profiles(id) not null,
  is_verified boolean default false,
  downloads_count bigint default 0,
  
  -- Marketplace Display Fields
  category text default 'dev', -- dev, business, personal, finance, marketing, engineering, research, fun
  icon text default '💻', -- Emoji or icon for card visual
  is_featured boolean default false, -- Featured on homepage
  is_top_seller boolean default false,
  roi_hours_saved int default 0, -- Hours saved per month
  
  -- Rating (can be computed from ratings table or cached here)
  avg_rating numeric(2,1) default 0,
  rating_count int default 0
);

-- Seed some initial skills for the marketplace
INSERT INTO skills (title, short_description, description, price, category, icon, is_verified, downloads_count, avg_rating, rating_count, roi_hours_saved, is_top_seller, author_id) VALUES
('FullStack_Architect_v9', 'Generate production-ready Next.js apps with Tailwind & Supabase.', 'Generate production-ready Next.js applications with Tailwind CSS, Supabase backend, and deployment pipelines.', 49, 'dev', '💻', true, 2400, 4.8, 127, 40, true, (SELECT id FROM profiles LIMIT 1)),
('Security_Auditor_Pro', 'Scan codebases for vulnerabilities and generate compliance reports.', 'Deep security analysis with CVE detection, dependency audits, and OWASP compliance checking.', 79, 'engineering', '🛡️', true, 890, 4.9, 89, 30, false, (SELECT id FROM profiles LIMIT 1)),
('Life_Coach_AI', 'Daily motivation, habit tracking, and guided journaling.', 'Your personal life optimization assistant with goal setting and progress tracking.', 19, 'personal', '🧘', true, 3800, 4.8, 294, 10, false, (SELECT id FROM profiles LIMIT 1)),
('Dating_Profile_Optimizer', 'AI bio writing, photo tips, and conversation starters.', 'Transform your dating profile with AI-powered optimization for Hinge, Bumble, and Tinder.', 29, 'personal', '💘', true, 6200, 4.6, 512, 15, false, (SELECT id FROM profiles LIMIT 1)),
('Market_Research_Agent', 'Deep competitive analysis with automatic sourcing.', 'Comprehensive market research with competitor tracking, trend analysis, and report generation.', 35, 'business', '📊', true, 1800, 4.7, 203, 25, false, (SELECT id FROM profiles LIMIT 1));


-- Set up RLS for Skills
alter table skills enable row level security;

create policy "Skills are viewable by everyone."
  on skills for select
  using ( true );

create policy "Users can insert their own skills."
  on skills for insert
  with check ( auth.uid() = author_id );

create policy "Users can update their own skills."
  on skills for update
  using ( auth.uid() = author_id );
-- Create a table for tracking subscription/purchase downloads
create table subscription_downloads (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  skill_id bigint references skills(id) not null,
  downloaded_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, skill_id)
);

-- RLS for subscription_downloads
alter table subscription_downloads enable row level security;

create policy "Users can view their own downloads."
  on subscription_downloads for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own downloads."
  on subscription_downloads for insert
  with check ( auth.uid() = user_id );

-- Create a table for skill ratings/reviews
create table ratings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  skill_id bigint references skills(id) not null,
  user_id uuid references auth.users not null,
  rating smallint check (rating >= 1 and rating <= 5) not null,
  comment text,
  
  unique(skill_id, user_id)
);

-- RLS for ratings
alter table ratings enable row level security;

create policy "Ratings are viewable by everyone."
  on ratings for select
  using ( true );

create policy "Users can insert their own ratings."
  on ratings for insert
  with check ( auth.uid() = user_id );

create policy "Users can update/delete their own ratings."
  on ratings for update
  using ( auth.uid() = user_id );
