-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for Skills/Protocols
create table skills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price numeric default 0,
  file_url text, -- Path to the .md file in Storage
  author_id uuid references profiles(id) not null,
  is_verified boolean default false,
  downloads_count bigint default 0
);

-- Set up RLS for Skills
alter table skills enable row level security;

create policy "Skills are viewable by everyone."
  on skills for select
  using ( true );

create policy "Users can insert their own skills."
  on skills for insert
  with check ( auth.uid() = author_id );

create policy "Users can update their own skills."
  on skills for update
  using ( auth.uid() = author_id );
